name: nisit-deeden      

include:
    - path: NisitDeeden-Webtech-backend/compose.yaml
      env_file: NisitDeeden-Webtech-backend/.env
    - path: NisitDeeden-Webtech-frontend/docker-compose.yml
      env_file: NisitDeeden-Webtech-frontend/.env
