name: nisit-deeden      

include:
    - path: NisitDeeden-Webtech-backend/compose.yaml
      env_file: NisitDeeden-Webtech-backend/.env
    - path: p2-final-project-sprint-procrastinator-v2/docker-compose.yml
      env_file: p2-final-project-sprint-procrastinator-v2/.env